### ISSUE TITLE
Run on Google Colab

### ISSUE THREAD

**Issue by apcameron** [mzbac/AutoGPTQ-API#1]
What would need to be done to get this running on Google Colab so you can connect to it remotely?

**Comment by ashercn97** [comment]
Yes!! This would b great to know!!

**Comment by mzbac** [comment]
If you want to host the API in Colab, you may have to use something like ngrok to do the tunneling. The main script for running the API will mostly be the same.

**Comment by ashercn97** [comment]
Okay i will look into it! Ty!

**Comment by ashercn97** [comment]
What part would i change to use ngrok?

**Comment by mzbac** [comment]
Please refer to the ngrok documentation for tunneling -> https://ngrok.com/docs/getting-started/
